### ISSUE TITLE
Detailed citations

### ISSUE THREAD

**Issue by Edelstadt** [Edelstadt/List-of-saints-template#2]
`<source>
            <url>
                <author/>
                <page_title>Svatý Mikuláš</page_title>
                <web_title>Wikipedie</web_title>
                <addrese>https://cs.wikipedia.org/wiki/Svat%C3%BD_Mikul%C3%A1%C5%A1</addrese>
                <date_visit>2016-03-10</date_visit>
                <date_citation>2016-03-15</date_citation>
                                <relate_to>`**date**`</relate_to>
                                <relate_to>`**name lang="CS"**`</relate_to>
            </url>
        </source>`

another idea? how to specify a citations?

**Comment by honzajavorek** [comment]
Maybe there already is an XML format for describing citations? https://en.wikipedia.org/wiki/Citation_Style_Language You could choose one you like and use it.

**Comment by Edelstadt** [comment]
Very nice!
It will definitely come handy in the future, however I expressed myself wrong. It's not about a citation form, I just need basic information for eventual generated citation. But even that ain't a purpose. It concerns me how (where) or even if to mention in detail, which citation binds to which data (when there are multiple sources). If I had two sources (and more), for example: citation_1 binds to name_cz, name_en, etc. and citation_2 binds to date (of celebration), beginning of celebration, etc. Or contrariwise: for each item have a reference to citation: name_cz -> citation_1, name_en->citation_1..., date->citation_2... Personaly I prefer the first solution, but how to write it elegantly into a template?

**Comment by honzajavorek** [comment]
So it's about pairing citations with names. One item can have multiple names and each name can have multiple citations.

XML has a concept of ID attribute. Value of ID has to be unique within the document and you can use it to reference the element from other place. Example:

``` xml
<something>
    <names>
        <name lang="cs" sources="523 266">Český Svátek</name>
        <name lang="en" sources="979">Czech Holiday</name>
        ...
    </names>
    <citations>
        <citation id="523">...</citation>
        <citation id="979">...</citation>
        <citation id="266">...</citation>
    </citations>
</something>
```

This way, it'd be probably also more effective to keep all your citations in separate document and reference them from various places than to have them listed separately with each holiday.

**Comment by Edelstadt** [comment]
Done, very thanks :+1: #
